package com.example.recycleme.search;

import com.example.recycleme.model.RecycledItem;
import com.example.recycleme.util.tree.AVLTreeItem;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;

/**
 * This class represents the search expression generated by parsing the input search query.
 * It provides the search results after evaluating the generated search expression consisting of
 * item name, list of brand names and a list of materials.
 * @author Devansu Yadav
 */
public class SearchExp {
    private String item;
    private HashSet<String> brand;
    private HashSet<String> material;

    public SearchExp(String item, HashSet<String> brand, HashSet<String> material) {
        this.item = item;
        this.brand = brand;
        this.material = material;
    }

    public String show() {
        return "Item: " + item + "; Brand: " + brand.toString() + "; Material: " + material.toString();
    }

    /**
     * Method that evaluates the search expression by searching items in the AVL tree based on
     * item name, brand names, and materials producing search results which are then
     * combined together and returned.
     */
    public List<RecycledItem> evaluateSearchExp(AVLTreeItem avlTreeItem) {
        String searchItem = item != null ? item: "";
        List<RecycledItem> result = new ArrayList<>();
        List<RecycledItem> resultMaterial = new ArrayList<>();

        for (String b : brand) {
            result.addAll(avlTreeItem.findItems(searchItem, b, ""));
        }

        for (String m : material) {
            resultMaterial.addAll(avlTreeItem.findItems(searchItem, "", m));
        }

        if (brand.isEmpty() && material.isEmpty()) {
            result.addAll(avlTreeItem.findItems(searchItem, "", ""));
        } else if (brand.isEmpty() || material.isEmpty()) {
            result.addAll(resultMaterial);
        } else {
            result.retainAll(resultMaterial);
        }
        return result;
    }

    public String getItem() {
        return item;
    }

    public HashSet<String> getBrand() {
        return brand;
    }

    public HashSet<String> getMaterial() {
        return material;
    }
}
